redis:
  use: false
  host: "localhost"
  port: 6379
  auth:
    enabled: false
    password: ""
  channel-id: 0

mongo:
  use: false
  use-uri: false
  host: "localhost"
  port: 27017
  database: "Flash" # use this to determine the db name
  auth:
    enabled: false
    username: ""
    password: ""
    auth-db: ""
